name: mne
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.0=py38h50d1736_1002
  - apptools=4.5.0=pyh9f0ad1d_1
  - argon2-cffi=20.1.0=py38h7e3306e_2
  - asciitree=0.3.3=py_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - blosc=1.20.1=hb1e8313_0
  - brotli=1.0.9=hb1e8313_3
  - brotlipy=0.7.0=py38h94c058a_1001
  - brunsli=0.1=hb1e8313_0
  - bzip2=1.0.8=haf1e3a3_3
  - c-ares=1.17.1=hc929b4f_0
  - ca-certificates=2020.12.5=h033912b_0
  - cached-property=1.5.1=py_0
  - certifi=2020.12.5=py38h50d1736_1
  - cffi=1.14.4=py38h6afc60c_0
  - cftime=1.3.0=py38hfb243c8_0
  - chardet=3.0.4=py38h5347e94_1008
  - charls=2.1.0=h4a8c4bd_2
  - cloudpickle=1.6.0=py_0
  - configobj=5.0.6=py_0
  - cryptography=3.2.1=py38h5c1d3f9_0
  - curl=7.71.1=hcb81553_8
  - cvxpy=1.1.7=py38h11c0d25_0
  - cvxpy-base=1.1.7=py38h6be0db6_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h4d0b108_1
  - dask-core=2.30.0=py_0
  - dbus=1.13.6=h0c50699_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dipy=1.3.0=py38hf3d72b9_1
  - double-conversion=3.1.5=h4a8c4bd_2
  - ecos=2.0.7.post1=py38hf3d72b9_3
  - eigen=3.3.8=h6516342_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - envisage=4.9.2=pyh9f0ad1d_1
  - expat=2.2.9=hb1e8313_2
  - fasteners=0.14.1=py_3
  - ffmpeg=4.3.1=he496704_1
  - freetype=2.10.4=h3f75d11_0
  - future=0.18.2=py38h50d1736_2
  - gettext=0.19.8.1=haf92f58_1004
  - giflib=5.2.1=hbcb3906_2
  - gl2ps=1.4.2=ha233b18_0
  - glew=2.1.0=h4a8c4bd_0
  - glib=2.66.3=h519c658_0
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.6=nompi_h4444151_1111
  - icu=67.1=hb1e8313_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2020.5.30=py38h5c28ed5_4
  - imageio=2.9.0=py_0
  - imageio-ffmpeg=0.4.2=py_0
  - importlib-metadata=3.1.0=pyhd8ed1ab_0
  - importlib_metadata=3.1.0=hd8ed1ab_0
  - ipykernel=5.3.4=py38h9bb44b7_1
  - ipython=7.19.0=py38h9bb44b7_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jedi=0.17.2=py38h50d1736_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=hbcb3906_0
  - jsoncpp=1.8.4=ha1b3eb9_1002
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_core=4.7.0=py38h50d1736_0
  - jupyter_nbextensions_configurator=0.4.1=py38h50d1736_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jxrlib=1.1=h0b31af3_2
  - kiwisolver=1.3.1=py38h9250c2b_0
  - krb5=1.17.2=h60d9502_0
  - lame=3.100=h1de35cc_1001
  - lcms2=2.11=h11f7e16_1
  - lerc=2.2=hb1e8313_0
  - libaec=1.0.4=h4a8c4bd_1
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libclang=10.0.1=default_hf57f61e_1
  - libcurl=7.71.1=h9bf37e3_8
  - libcxx=11.0.0=h4c3b8ed_1
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.2.1=hb1e8313_1007
  - libgfortran=5.0.0=h7cc5361_13
  - libgfortran5=9.3.0=h7cc5361_13
  - libglib=2.66.3=h2575888_0
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=3_openblas
  - libllvm10=10.0.1=h009f743_3
  - libnetcdf=4.7.4=nompi_h4844aed_106
  - libnghttp2=1.41.0=h7580e61_2
  - libogg=1.3.2=h0b31af3_1002
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libpq=12.3=haa216e0_2
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=h8a08a2b_5
  - libtheora=1.1.1=haf1e3a3_1004
  - libtiff=4.1.0=hca7d577_6
  - libvorbis=1.3.7=h4a8c4bd_0
  - libwebp-base=1.1.0=hbcb3906_3
  - libxml2=2.9.10=h2c6e4a5_2
  - libzopfli=1.0.3=h4a8c4bd_0
  - llvm-openmp=11.0.0=h73239a0_1
  - llvmlite=0.34.0=py38h3707e27_2
  - loguru=0.5.3=py38h32f6830_2
  - lz4-c=1.9.2=hb1e8313_3
  - markupsafe=1.1.1=py38h94c058a_2
  - matplotlib=3.3.3=py38h50d1736_0
  - matplotlib-base=3.3.3=py38h9bfd75d_0
  - mayavi=4.7.2=py38haf0748e_4
  - meshio=4.3.5=pyhd8ed1ab_0
  - mffpy=0.5.8=pyhd8ed1ab_0
  - mistune=0.8.4=py38h7e3306e_1002
  - mne=0.21.2=py38h50d1736_0
  - mock=4.0.2=py38h32f6830_1
  - monotonic=1.5=py_0
  - msgpack-python=1.0.2=py38hd9c93a9_1
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hfb8f7af_2
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - netcdf4=1.5.4=nompi_py38he235a2f_103
  - nettle=3.6=hedd7734_0
  - networkx=2.5=py_0
  - nibabel=3.2.0=py_0
  - nilearn=0.7.0=pyhd8ed1ab_0
  - notebook=6.1.5=py38h50d1736_0
  - nspr=4.29=hb1e8313_1
  - nss=3.47=hc0980d9_0
  - numba=0.51.2=py38h6be0db6_0
  - numcodecs=0.7.3=py38h23ab428_0
  - numexpr=2.7.1=py38h6be0db6_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=hd174df1_0
  - openjpeg=2.3.1=h254dc36_3
  - openssl=1.1.1k=h0d85af4_0
  - osqp=0.6.1=py38h5fc983b_2
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.4=py38hcf432d8_0
  - pandoc=2.11.2=hc929b4f_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py38h565d989_0
  - proj=7.1.1=h45baca5_3
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - prompt_toolkit=3.0.8=hd8ed1ab_0
  - psutil=5.7.3=py38h94c058a_0
  - ptyprocess=0.6.0=py_1001
  - pugixml=1.10=hb1e8313_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pydicom=2.1.0=pyhd3deb0d_0
  - pyface=7.1.0=pyh9f0ad1d_0
  - pygments=2.7.2=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38hca2ab18_4
  - pyrsistent=0.17.3=py38h7e3306e_1
  - pysocks=1.7.1=py38h5347e94_2
  - pysurfer=0.11.0=py_0
  - pytables=3.6.1=py38h4e4ac5c_3
  - python=3.8.6=hcfdab8c_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-picard=0.4=pyh5ca1d4c_1
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - pyvista=0.27.2=pyhd8ed1ab_0
  - pyvistaqt=0.2.0=py_0
  - pywavelets=1.1.1=py38h174b24a_3
  - pyyaml=5.3.1=py38h94c058a_1
  - pyzmq=20.0.0=py38h9b3f83f_1
  - qt=5.12.9=h717870c_0
  - qtconsole=5.0.1=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h0678c8f_2
  - requests=2.25.0=pyhd3deb0d_0
  - scikit-image=0.17.2=py38hcf432d8_4
  - scikit-learn=0.23.2=py38h740a60c_3
  - scipy=1.5.3=py38hb6cd474_0
  - scooby=0.5.6=pyh9f0ad1d_0
  - scs=2.1.2=py38hd88393d_2
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h5347e94_2
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=hb1e8313_3
  - spyder-kernels=1.10.0=py38h50d1736_0
  - sqlite=3.33.0=h960bd1c_1
  - statsmodels=0.12.1=py38hfb243c8_1
  - tbb=2019.9=ha1b3eb9_1
  - tbb-devel=2019.9=ha1b3eb9_1
  - terminado=0.9.1=py38h50d1736_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.11.18=pyhd8ed1ab_0
  - tk=8.6.10=hb0a8c7a_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h7e3306e_0
  - tqdm=4.53.0=pyhd8ed1ab_1
  - traitlets=5.0.5=py_0
  - traits=6.1.1=py38h7e3306e_0
  - traitsui=7.1.0=pyh9f0ad1d_0
  - urllib3=1.25.11=py_0
  - utfcpp=3.1.2=0
  - vtk=9.0.1=no_osmesa_py38h523a0c9_102
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38h50d1736_4
  - wurlitzer=2.0.0=py38h32f6830_2
  - x264=1!152.20180806=h1de35cc_0
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - zarr=2.7.0=pyhd8ed1ab_0
  - zeromq=4.3.3=h74dc148_3
  - zfp=0.5.5=hb1e8313_4
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.5=h289c70a_2
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - autoreject==0.2.2
    - cachetools==4.1.1
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - mne-features==0.1
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pip==21.0.1
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-rvm==0.1.0a1
    - sklearn-rvm==0.1.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.1
    - tensorflow-addons==0.11.2
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.5.0.dev2020123101
    - typeguard==2.10.0
    - typing-extensions==3.7.4.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
